POST http://localhost:3000/user
content-type: application/json

{
    "email": "georg@boulder.at",
    "password": "georgPrassl"
}

###
POST http://localhost:3000/boulder
content-type: application/json

{
    "name": "TestBoulder",
    "colour": 1,
    "difficulty": 1,
    "locationId": 1,
    "creatorId": 5 
}

###
PUT http://localhost:3000/boulder/59
content-type: application/json

{
    "name": "Awesome Boulder",
    "colour": 1,
    "difficulty": 1,
    "locationId": 1,
    "changeUserId": 5 
}


###

GET http://localhost:3000/boulder/5


###
POST http://localhost:3000/boulderInteraction
content-type: application/json

{
    "boulderId": 59, 
    "userId": 2,
    "comment": "Testkommentar",
    "status": 1
}

###
GET http://localhost:3000/boulderInteraction/59

###
PUT http://localhost:3000/boulderInteraction/1
content-type: application/json

{
    "comment": "Test",
    "status": 5
}

###
POST http://localhost:3000/like/53
content-type: application/json

{
    "userId": 2
}

###
DELETE http://localhost:3000/like/53
content-type: application/json

{
    "userId": 2
}

###